version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db
    networks:
      - fullcycle-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=fullcycle-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - db
      - app
    networks:
      - fullcycle-network

networks:
  fullcycle-network:
    driver: bridge
